SHELL=/usr/bin/env bash

all: build
.PHONY: all

migrate:
	rm -f migrate
	go build $(GOFLAGS) -o migrate ./tools/migrate

test:
	rm -f testobj
	go build $(GOFLAGS) -o testobj ./tools/test

partation:
	rm -f partation
	go build $(GOFLAGS) -o partation ./tools/checkPartition